---
version: 2
project_name: ggezchaind

env:
  - GO111MODULE=on
  - CGO_ENABLED=1

before:
  hooks:
    - sudo wget https://github.com/CosmWasm/wasmvm/releases/download/v2.2.1/checksums.txt -O /home/rami/test-go/checksums.txt

builds:
  - id: ggezchaind-darwin-amd64
    main: ./cmd/ggezchaind/main.go
    binary: ggezchaind
    hooks:
      pre:
        - sudo wget https://github.com/CosmWasm/wasmvm/releases/download/v2.2.1/libwasmvmstatic_darwin.a -O /lib/libwasmvmstatic_darwin.a
        # verify checksum
        - sha256sum /lib/libwasmvmstatic_darwin.a | grep $(cat /home/rami/test-go/checksums.txt | grep libwasmvmstatic_darwin | cut -d ' ' -f 1) || exit 1
    env:
      - CC=o64-clang
      - CGO_LDFLAGS=-L/lib
    goos:
      - darwin
    goarch:
      - amd64
    flags:
      - -mod=readonly
      - -trimpath
    ldflags:
      - -X github.com/cosmos/cosmos-sdk/version.Name=ggezchain
      - -X github.com/cosmos/cosmos-sdk/version.AppName=ggezchaind
      - -X github.com/cosmos/cosmos-sdk/version.Version={{ .Version }}
      - -X github.com/cosmos/cosmos-sdk/version.Commit={{ .ShortCommit }}
      - -X github.com/cosmos/cosmos-sdk/version.BuildTags=netgo,ledger,static_wasm
      - -X github.com/cometbft/cometbft/version.TMCoreSemVer=v1.0.1
      - -w -s
      - -linkmode=external
    tags:
      - netgo
      - ledger
      - pebbledb
      - static_wasm

  - id: ggezchaind-darwin-arm64
    main: ./cmd/ggezchaind/main.go
    binary: ggezchaind
    hooks:
      pre:
        - sudo wget https://github.com/CosmWasm/wasmvm/releases/download/v2.2.1/libwasmvmstatic_darwin.a -O /lib/libwasmvmstatic_darwin.a
        # verify checksum
        - sha256sum /lib/libwasmvmstatic_darwin.a | grep $(cat /home/rami/test-go/checksums.txt | grep libwasmvmstatic_darwin | cut -d ' ' -f 1) || exit 1
    env:
      - CC=oa64-clang
      - CGO_LDFLAGS=-L/lib
    goos:
      - darwin
    goarch:
      - arm64
    flags:
      - -mod=readonly
      - -trimpath
    ldflags:
      - -X github.com/cosmos/cosmos-sdk/version.Name=ggezchain
      - -X github.com/cosmos/cosmos-sdk/version.AppName=ggezchaind
      - -X github.com/cosmos/cosmos-sdk/version.Version={{ .Version }}
      - -X github.com/cosmos/cosmos-sdk/version.Commit={{ .ShortCommit }}
      - -X github.com/cosmos/cosmos-sdk/version.BuildTags=netgo,ledger,static_wasm
      - -X github.com/cometbft/cometbft/version.TMCoreSemVer=v1.0.1
      - -w -s
      - -linkmode=external
    tags:
      - netgo
      - ledger
      - pebbledb
      - static_wasm

  - id: ggezchaind-linux-amd64
    main: ./cmd/ggezchaind
    binary: ggezchaind
    hooks:
      pre:
        - sudo apt install -y linux-headers-generic
        - sudo wget https://github.com/CosmWasm/wasmvm/releases/download/v2.2.1/libwasmvm_muslc.x86_64.a -O /lib/libwasmvm_muslc.x86_64.a
        # verify checksum
        - sha256sum /lib/libwasmvm_muslc.x86_64.a | grep $(cat /home/rami/test-go/checksums.txt | grep libwasmvm_muslc.x86_64 | cut -d ' ' -f 1) || exit 1
    goos:
      - linux
    goarch:
      - amd64
    flags:
      - -mod=readonly
      - -trimpath
    ldflags:
      - -X github.com/cosmos/cosmos-sdk/version.Name=ggezchain
      - -X github.com/cosmos/cosmos-sdk/version.AppName=ggezchaind
      - -X github.com/cosmos/cosmos-sdk/version.Version={{ .Version }}
      - -X github.com/cosmos/cosmos-sdk/version.Commit={{ .ShortCommit }}
      - -X github.com/cosmos/cosmos-sdk/version.BuildTags=netgo,ledger,muslc,osusergo
      - -X github.com/cometbft/cometbft/version.TMCoreSemVer=v1.0.1
      - -w -s
      - -linkmode=external
      - -extldflags '-Wl,-z,muldefs -static -lm'
    tags:
      - netgo
      - ledger
      - muslc
      - osusergo
      - pebbledb

  - id: ggezchaind-linux-arm64
    main: ./cmd/ggezchaind
    binary: ggezchaind
    hooks:
      pre:
        - sudo apt install -y linux-headers-generic
        - sudo wget https://github.com/CosmWasm/wasmvm/releases/download/v2.2.1/libwasmvm_muslc.aarch64.a -O /lib/libwasmvm_muslc.aarch64.a
        # verify checksum
        - sha256sum /lib/libwasmvm_muslc.aarch64.a | grep $(cat /home/rami/test-go/checksums.txt | grep libwasmvm_muslc.aarch64 | cut -d ' ' -f 1) || exit 1
    goos:
      - linux
    goarch:
      - arm64
    flags:
      - -mod=readonly
      - -trimpath
    ldflags:
      - -X github.com/cosmos/cosmos-sdk/version.Name=ggezchain
      - -X github.com/cosmos/cosmos-sdk/version.AppName=ggezchaind
      - -X github.com/cosmos/cosmos-sdk/version.Version={{ .Version }}
      - -X github.com/cosmos/cosmos-sdk/version.Commit={{ .ShortCommit }}
      - -X github.com/cosmos/cosmos-sdk/version.BuildTags=netgo,ledger,muslc,osusergo
      - -X github.com/cometbft/cometbft/version.TMCoreSemVer=v1.0.1
      - -w -s
      - -linkmode=external
      - -extldflags '-Wl,-z,muldefs -static -lm'
    tags:
      - netgo
      - ledger
      - muslc
      - osusergo
      - pebbledb

archives:
  - id: zipped
    builds:
      - ggezchaind-linux-amd64
      - ggezchaind-linux-arm64
      - ggezchaind-darwin-amd64
      - ggezchaind-darwin-arm64
    name_template: "{{.ProjectName}}-{{ .Version }}-{{ .Os }}-{{ .Arch }}"
    format: tar.gz
    files:
      - none*
  - id: binaries
    builds:
      - ggezchaind-linux-amd64
      - ggezchaind-linux-arm64
      - ggezchaind-darwin-amd64
      - ggezchaind-darwin-arm64
    name_template: "{{.ProjectName}}-{{ .Version }}-{{ .Os }}-{{ .Arch }}"
    format: binary
    files:
      - none*

checksum:
  name_template: "sha256sum.txt"
  algorithm: sha256

# Docs: https://goreleaser.com/customization/changelog/
changelog:
  disable: true

# Docs: https://goreleaser.com/customization/release/
release:
  github:
    owner: "ramiqadoumi"
    name: "ggezchain"
  replace_existing_draft: true
  header: |
    < DESCRIPTION OF RELEASE >

    ## Changelog

    See the full changelog [here](https://github.com/ramiqadoumi/ggezchain/blob/v{{ .Version }}/CHANGELOG.md)

    #### 🔨 Build from source

    If you prefer to build from source, you can use the following commands:

    ````bash
    git clone https://github.com/ramiqadoumi/ggezchain
    cd ggezchain && git checkout v{{ .Version }}
    make install
    ````

  name_template: "ggezchain v{{.Version}}"
  mode: replace
  draft: true
# Docs: https://goreleaser.com/customization/announce/
# We could automatically announce the release in
# - discord
# - slack
# - twitter
# - webhooks
# - telegram
# - reddit
#
# announce:
# discord:
#   enabled: true
#   message_template: 'New {{.Tag}} is out!'
