version: 1
accounts:
- name: mutaz
  coins:
  - 20000000000uggez
  - 200000000uggez1
- name: mohd
  coins:
  - 10000000000uggez
  - 100000000uggez1
client:
  openapi:
    path: docs/static/openapi.yml
faucet:
  name: mohd
  coins:
  - 5000000uggez
  - 100000uggez1
validators:
- name: mutaz
  bonded: 100000000uggez1
