version: 1
accounts:
  - name: mutaz
    coins: ["20000000000uggez", "200000000stake"]
    mnemonic: later rookie jazz alter minute group share scan random try brain brain task afraid roast fuel ring autumn awake diamond length sadness please round
  - name: mohd
    coins: ["10000000000uggez", "100000000stake"]
    mnemonic: float elder spice lamp blue cause office surge reopen brass stone garbage pistol noodle breeze fortune jewel flavor asthma dirt rubber lyrics vicious picnic
validators:
  - name: mutaz
    bonded: "100000000stake" 
client:
  openapi:
    path: "docs/static/openapi.yml"
  typescript:
    path: "ts-client"
  vuex:
    path: "vue/src/store"
faucet:
  name: mohd
  coins: ["5000000uggez", "100000stake"]
