version: 1
accounts:
  - name: mutaz
    coins: ["20000000000uggez", "200000000stake"]
  - name: mohd
    coins: ["10000000000uggez", "100000000stake"]
validators:
  - name: mutaz
    bonded: "100000000stake" 
client:
  openapi:
    path: "docs/static/openapi.yml"
  typescript:
    path: "ts-client"
  vuex:
    path: "vue/src/store"
faucet:
  name: mohd
  coins: ["5000000uggez", "100000stake"]
